### ISSUE TITLE
Binding HPC usage or home storage data to usernames not always successfully 

### ISSUE THREAD

**Issue by Li-ReDBox** [eResearchSA/reporting-frontend#27]
At least in admin mode, if a user clicks HPC Summary too quickly, downloading usage data, calculating summaries and binding to usernames completed before usernames have been downloaded, the data are not fully linked. The result conditional on search criteria is cached and the calculation cannot be re-done.

Code should allow re-calculate - rebind.

**Comment by tomsaleeba** [comment]
I recommend using ui-router's resolve function on the HPC states that are causing problems: https://github.com/angular-ui/ui-router/wiki#resolve

**Comment by tomsaleeba** [comment]
Steps:
-launch portal as an admin
-navigate to admin/storage/hpcStorage
-click "view usage" before all the "get_access/" HTTP calls have completed

Expected behaviour:
Something happens that means we don't see incomplete data.

Actual behaviour:
We are shown data that looks ok but it's not complete. If you note the current number of rows then reload the page, wait for the "get_access/" calls to complete and click "view usage" you'll see more rows show up.

**Comment by tomsaleeba** [comment]
Done and pushed to dev branch.
