### ISSUE TITLE
Naitaonl storage page: spinning wheel sometimes does not stop

### ISSUE THREAD

**Issue by Li-ReDBox** [eResearchSA/reporting-frontend#42]
This is a random event. In my tests, if a monthly report finishes correctly, by not changing the month just clicking "View Usage", it is likely to trigger the error.

The error itself does not make sense to me. Even Chromium gives the line of code in the trap I cannot see which part of code needs to be looked at.

![image](https://cloud.githubusercontent.com/assets/3203171/25415250/9f472444-2a75-11e7-800b-1cd2ccd82390.png)

**Comment by tomsaleeba** [comment]
It's related to this function:
https://github.com/eResearchSA/reporting-frontend/blob/dev/js/services/rollerUpperer.js#L44
You can see that it will `throw` if the values are the same. I assumed that we should check that records we are combining should be the same so we don't lose values but maybe I assumed wrong.

**Comment by tomsaleeba** [comment]
Fixed and pushed to `dev` branch.

The rollup is still checking fields for equality but it will ignore when one of the values is undefined. It will still `throw` when a problem is found but now it does `throw new Error(...` so we get stacktrace information.

The rollerUpperer seems to work well in admin mode because all user data is available but it will cause issues if we decide to run it for non-admin. There's at least 3 instances of users being under one organisation but filesystems they are assigned to are under another organisation. This causes an issue for the rollup because we will be missing user information and won't be able to do the join as parts of the join key will be missing.
